--仓库结存
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	WH.NAME AS HOUSE_NAME,
	SUM(VOLUME) AS VOLUME,
	0 AS WORKSHOP_VOLUME,
	0 AS SUPPLIER_VOLUME,
	0 AS PLAN_VOLUME
FROM 
(
	SELECT 
		WAREHOUSE_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_MATERIAL_BALANCE
	UNION ALL
	SELECT 
		WAREHOUSE_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_MATERIAL_BALANCE
) CMB 
LEFT JOIN WAREHOUSE WH ON CMB.WAREHOUSE_ID = WH.ID
LEFT JOIN T_MATERIAL TM ON CMB.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE WH.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,WH.NAME;

--车间结存
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	WS.NAME AS HOUSE_NAME,
	0 AS VOLUME,
	SUM(VOLUME) AS WORKSHOP_VOLUME,
	0 AS SUPPLIER_VOLUME,
	0 AS PLAN_VOLUME
FROM 
(
	SELECT 
		WORKSHOP_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_WORKSHOP_PRICE
	UNION ALL
	SELECT 
		WORKSHOP_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_WORKSHOP_BALANCE
) CWP 
LEFT JOIN WORKSHOP WS ON CWP.WORKSHOP_ID = WS.ID
LEFT JOIN T_MATERIAL TM ON CWP.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE WS.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,WS.NAME;


--加工商结存
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	SP.NAME AS HOUSE_NAME,
	0 AS VOLUME,
	0 AS WORKSHOP_VOLUME,
	SUM(VOLUME) AS SUPPLIER_VOLUME,
	SUM(BALANCE) AS PLAN_VOLUME
FROM 
(
	SELECT 
		SUPPLIER_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_CONSIGN_PROCESSED_PRICE
	UNION ALL
	SELECT 
		SUPPLIER_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_CONSIGN_BALANCE
) CCP 
LEFT JOIN PUR_PLAN_BALANCE PPB ON CCP.SUPPLIER_ID = PPB.CCP.SUPPLIER_ID AND CCP.MATERIAL_ID = PPB.MATERIAL_ID
LEFT JOIN SUPPLIER SP ON CCP.SUPPLIER_ID = SP.ID
LEFT JOIN T_MATERIAL TM ON CCP.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE SP.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,SP.NAME;

--总统计SQL
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	WH.NAME AS HOUSE_NAME,
	SUM(IFNULL(VOLUME,0)) AS VOLUME,
	0 AS WORKSHOP_VOLUME,
	0 AS SUPPLIER_VOLUME,
	0 AS PLAN_VOLUME
FROM 
(
	SELECT 
		WAREHOUSE_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_MATERIAL_BALANCE
	UNION ALL
	SELECT 
		WAREHOUSE_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_MATERIAL_BALANCE
) CMB 
LEFT JOIN WAREHOUSE WH ON CMB.WAREHOUSE_ID = WH.ID
LEFT JOIN T_MATERIAL TM ON CMB.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE WH.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,WH.NAME
UNION ALL
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	WS.NAME AS HOUSE_NAME,
	0 AS VOLUME,
	SUM(IFNULL(VOLUME,0)) AS WORKSHOP_VOLUME,
	0 AS SUPPLIER_VOLUME,
	0 AS PLAN_VOLUME
FROM 
(
	SELECT 
		WORKSHOP_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_WORKSHOP_PRICE
	UNION ALL
	SELECT 
		WORKSHOP_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_WORKSHOP_BALANCE
) CWP 
LEFT JOIN WORKSHOP WS ON CWP.WORKSHOP_ID = WS.ID
LEFT JOIN T_MATERIAL TM ON CWP.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE WS.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,WS.NAME
UNION ALL
SELECT
	TM.NUMBER,
	TM.NAME AS MATERIAL_NAME,
	UT.NAME AS UNIT_NAME,
	SP.NAME AS HOUSE_NAME,
	0 AS VOLUME,
	0 AS WORKSHOP_VOLUME,
	SUM(IFNULL(VOLUME,0)) AS SUPPLIER_VOLUME,
	SUM(IFNULL(BALANCE,0)) AS PLAN_VOLUME
FROM 
(
	SELECT 
		SUPPLIER_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_CONSIGN_PROCESSED_PRICE
	UNION ALL
	SELECT 
		SUPPLIER_ID,
		MATERIAL_ID,
		VOLUME
	FROM CUR_SAVE_CONSIGN_BALANCE
) CCP 
LEFT JOIN PUR_PLAN_BALANCE PPB ON CCP.SUPPLIER_ID = PPB.CCP.SUPPLIER_ID AND CCP.MATERIAL_ID = PPB.MATERIAL_ID
LEFT JOIN SUPPLIER SP ON CCP.SUPPLIER_ID = SP.ID
LEFT JOIN T_MATERIAL TM ON CCP.MATERIAL_ID = TM.ID
LEFT JOIN UNIT UT ON TM.DEFAULT_UNIT_ID = UT.ID
WHERE SP.NAME IS NOT NULL AND TM.NAME IS NOT NULL
GROUP BY TM.NUMBER,TM.NAME,UT.NAME,SP.NAME